[dolinews-honeypot]
enabled  = true
filter   = dolinews-honeypot
# Sous nginx ou avec la couche Apache, ajouter une seconde ligne indentee
# pointant le journal du serveur web.
logpath  = {{LOG_DIR}}/honeypot.log
maxretry = 4
findtime = 1h
bantime  = 24h
bantime.increment = true
bantime.factor    = 2
bantime.maxtime   = 30d
banaction = %(banaction_allports)s
protocol  = all

[dolinews-honeypot-instant]
enabled  = true
filter   = dolinews-honeypot[level=instant]
logpath  = {{LOG_DIR}}/honeypot.log
maxretry = 1
findtime = 1h
bantime  = 24h
bantime.increment = true
bantime.factor    = 2
bantime.maxtime   = 30d
banaction = %(banaction_allports)s
protocol  = all
